package projectprogram;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.bson.Document;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author bryan
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogInfo = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iniBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jDialogInfo.setMaximumSize(new java.awt.Dimension(963, 599));
        jDialogInfo.setMinimumSize(new java.awt.Dimension(963, 599));
        jDialogInfo.setModal(true);
        jDialogInfo.getContentPane().setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/unknown.jpg"))); // NOI18N
        jDialogInfo.getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 50, 300, 300);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");
        jDialogInfo.getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 70, 37, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");
        jDialogInfo.getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 130, 37, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("jLabel10");
        jDialogInfo.getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 200, 43, 16);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("jLabel11");
        jDialogInfo.getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 270, 43, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("jLabel12");
        jDialogInfo.getContentPane().add(jLabel12);
        jLabel12.setBounds(400, 330, 43, 16);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("..........");
        jDialogInfo.getContentPane().add(jLabel13);
        jLabel13.setBounds(640, 80, 30, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("..........");
        jDialogInfo.getContentPane().add(jLabel14);
        jLabel14.setBounds(620, 140, 30, 16);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("..........");
        jDialogInfo.getContentPane().add(jLabel15);
        jLabel15.setBounds(660, 190, 30, 16);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("..........");
        jDialogInfo.getContentPane().add(jLabel16);
        jLabel16.setBounds(620, 250, 30, 16);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("..........");
        jDialogInfo.getContentPane().add(jLabel17);
        jLabel17.setBounds(600, 310, 30, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Preview.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jDialogInfo.getContentPane().add(jButton1);
        jButton1.setBounds(50, 470, 150, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Artist.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jDialogInfo.getContentPane().add(jButton2);
        jButton2.setBounds(240, 470, 130, 50);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Track.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jDialogInfo.getContentPane().add(jButton3);
        jButton3.setBounds(410, 470, 130, 50);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Album.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jDialogInfo.getContentPane().add(jButton4);
        jButton4.setBounds(570, 470, 130, 50);

        jButton5.setText("jButton5");
        jDialogInfo.getContentPane().add(jButton5);
        jButton5.setBounds(820, 470, 75, 22);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Rectangle 24.png"))); // NOI18N
        jDialogInfo.getContentPane().add(jLabel19);
        jLabel19.setBounds(-150, -30, 1110, 600);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Rectangle 15.png"))); // NOI18N
        jDialogInfo.getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 960, 600);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(444, 629));
        setMinimumSize(new java.awt.Dimension(444, 629));
        setPreferredSize(new java.awt.Dimension(444, 629));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Welcome to");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 270, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Frame (2).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 160, 340, 320);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Get started");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 530, 100, 20);

        iniBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/2 button.png"))); // NOI18N
        iniBtn.setBorder(null);
        iniBtn.setBorderPainted(false);
        iniBtn.setContentAreaFilled(false);
        iniBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniBtnActionPerformed(evt);
            }
        });
        getContentPane().add(iniBtn);
        iniBtn.setBounds(0, 500, 430, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/black bg.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 290, 430, 400);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/note.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, -30, 660, 490);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Blue.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-30, -10, 520, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniBtnActionPerformed
        MongoClient client = MongoClients.create("mongodb+srv://BryanDB:DTrUZ0em3XONr3fR@quintanabryan-g.dobuj.mongodb.net/?retryWrites=true&w=majority");

        MongoDatabase db = client.getDatabase("Music");

        MongoCollection<Document> toys = db.getCollection("MusicInfo");

        Document doc = toys.find().first();

        try (MongoCursor<Document> cur = toys.find().iterator()) {

            while (cur.hasNext()) {

                doc = cur.next();
                var users = new ArrayList<>(doc.values());

                System.out.println("S" + users.get(1) + users.get(2));
            }
        }
        JFrame frame = new JFrame();

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setBounds(100, 100, 1920, 1080);
        frame.getContentPane().setLayout(null);

        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setBounds(10, 101, 1900, 900);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        //scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        getContentPane().add(scrollPane);

        JPanel borderlaoutpanel = new JPanel();
        scrollPane.setViewportView(borderlaoutpanel);
        borderlaoutpanel.setLayout(new BorderLayout(0, 0));

        JPanel columnpanel = new JPanel();
        borderlaoutpanel.add(columnpanel, BorderLayout.NORTH);
        columnpanel.setLayout(new GridLayout(0, 1, 0, 1));
        columnpanel.setBackground(Color.gray);

        for (int i = 0; i < 32; i++) {
            JPanel rowPanel = new JPanel();
            rowPanel.setPreferredSize(new Dimension(300, 30));
            columnpanel.add(rowPanel);
            rowPanel.setLayout(null);

            JButton button = new JButton("" + (i + 1));

            button.setBounds(20, 5, 89, 23);
            rowPanel.add(button);
            
            JLabel showTitle = new JLabel("Song's title");
            showTitle.setBounds(125, 5, 89, 23);
            rowPanel.add(showTitle);
            
            JLabel showArtist = new JLabel("Artist's title");
            showArtist.setBounds(225, 5, 89, 23);
            rowPanel.add(showArtist);
            
            JLabel showAlbum = new JLabel("Album's title");
            showAlbum.setBounds(325, 5, 89, 23);
            rowPanel.add(showAlbum);
            
            JLabel showDuration = new JLabel("Duration time");
            showDuration.setBounds(425, 5, 89, 23);
            rowPanel.add(showDuration);
            

            if (i % 2 == 0) {
                rowPanel.setBackground(SystemColor.inactiveCaptionBorder);
            }

            ActionListener oyente = new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {

                    System.out.println(((JButton) e.getSource()).getText());
                    jDialogInfo.setVisible(true);
                }
            };

            button.addActionListener(oyente);

        }

        frame.add(scrollPane);
        this.setVisible(false);
        frame.setVisible(true);


    }//GEN-LAST:event_iniBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialogInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
